services:
  db:
    image: postgres:15
    container_name: finance_postgres
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"